#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancersBook
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="adsrush")]
	public partial class jobsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_FreelancersBook_JobsApply(Table_FreelancersBook_JobsApply instance);
    partial void UpdateTable_FreelancersBook_JobsApply(Table_FreelancersBook_JobsApply instance);
    partial void DeleteTable_FreelancersBook_JobsApply(Table_FreelancersBook_JobsApply instance);
    partial void InsertTable_FreelancersBook_JobsReject(Table_FreelancersBook_JobsReject instance);
    partial void UpdateTable_FreelancersBook_JobsReject(Table_FreelancersBook_JobsReject instance);
    partial void DeleteTable_FreelancersBook_JobsReject(Table_FreelancersBook_JobsReject instance);
    partial void InsertTable_FreelancersBook_JobsHired(Table_FreelancersBook_JobsHired instance);
    partial void UpdateTable_FreelancersBook_JobsHired(Table_FreelancersBook_JobsHired instance);
    partial void DeleteTable_FreelancersBook_JobsHired(Table_FreelancersBook_JobsHired instance);
    partial void InsertTable_FreelancersBook_Job(Table_FreelancersBook_Job instance);
    partial void UpdateTable_FreelancersBook_Job(Table_FreelancersBook_Job instance);
    partial void DeleteTable_FreelancersBook_Job(Table_FreelancersBook_Job instance);
    #endregion
		
		public jobsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["adsrushConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public jobsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public jobsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public jobsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public jobsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_FreelancersBook_JobsApply> Table_FreelancersBook_JobsApplies
		{
			get
			{
				return this.GetTable<Table_FreelancersBook_JobsApply>();
			}
		}
		
		public System.Data.Linq.Table<Table_FreelancersBook_JobsReject> Table_FreelancersBook_JobsRejects
		{
			get
			{
				return this.GetTable<Table_FreelancersBook_JobsReject>();
			}
		}
		
		public System.Data.Linq.Table<Table_FreelancersBook_JobsHired> Table_FreelancersBook_JobsHireds
		{
			get
			{
				return this.GetTable<Table_FreelancersBook_JobsHired>();
			}
		}
		
		public System.Data.Linq.Table<Table_FreelancersBook_Job> Table_FreelancersBook_Jobs
		{
			get
			{
				return this.GetTable<Table_FreelancersBook_Job>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_FreelancersBook_JobsApply")]
	public partial class Table_FreelancersBook_JobsApply : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _jobid;
		
		private string _usernameapply;
		
		private System.Nullable<int> _aidapply;
		
		private string _letter;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnjobidChanging(System.Nullable<int> value);
    partial void OnjobidChanged();
    partial void OnusernameapplyChanging(string value);
    partial void OnusernameapplyChanged();
    partial void OnaidapplyChanging(System.Nullable<int> value);
    partial void OnaidapplyChanged();
    partial void OnletterChanging(string value);
    partial void OnletterChanged();
    #endregion
		
		public Table_FreelancersBook_JobsApply()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobid", DbType="Int")]
		public System.Nullable<int> jobid
		{
			get
			{
				return this._jobid;
			}
			set
			{
				if ((this._jobid != value))
				{
					this.OnjobidChanging(value);
					this.SendPropertyChanging();
					this._jobid = value;
					this.SendPropertyChanged("jobid");
					this.OnjobidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usernameapply", DbType="NVarChar(1500)")]
		public string usernameapply
		{
			get
			{
				return this._usernameapply;
			}
			set
			{
				if ((this._usernameapply != value))
				{
					this.OnusernameapplyChanging(value);
					this.SendPropertyChanging();
					this._usernameapply = value;
					this.SendPropertyChanged("usernameapply");
					this.OnusernameapplyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aidapply", DbType="Int")]
		public System.Nullable<int> aidapply
		{
			get
			{
				return this._aidapply;
			}
			set
			{
				if ((this._aidapply != value))
				{
					this.OnaidapplyChanging(value);
					this.SendPropertyChanging();
					this._aidapply = value;
					this.SendPropertyChanged("aidapply");
					this.OnaidapplyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_letter", DbType="NVarChar(MAX)")]
		public string letter
		{
			get
			{
				return this._letter;
			}
			set
			{
				if ((this._letter != value))
				{
					this.OnletterChanging(value);
					this.SendPropertyChanging();
					this._letter = value;
					this.SendPropertyChanged("letter");
					this.OnletterChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_FreelancersBook_JobsReject")]
	public partial class Table_FreelancersBook_JobsReject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _jobid;
		
		private string _usernamerejected;
		
		private System.Nullable<int> _aidrejected;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnjobidChanging(System.Nullable<int> value);
    partial void OnjobidChanged();
    partial void OnusernamerejectedChanging(string value);
    partial void OnusernamerejectedChanged();
    partial void OnaidrejectedChanging(System.Nullable<int> value);
    partial void OnaidrejectedChanged();
    #endregion
		
		public Table_FreelancersBook_JobsReject()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobid", DbType="Int")]
		public System.Nullable<int> jobid
		{
			get
			{
				return this._jobid;
			}
			set
			{
				if ((this._jobid != value))
				{
					this.OnjobidChanging(value);
					this.SendPropertyChanging();
					this._jobid = value;
					this.SendPropertyChanged("jobid");
					this.OnjobidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usernamerejected", DbType="NVarChar(1500)")]
		public string usernamerejected
		{
			get
			{
				return this._usernamerejected;
			}
			set
			{
				if ((this._usernamerejected != value))
				{
					this.OnusernamerejectedChanging(value);
					this.SendPropertyChanging();
					this._usernamerejected = value;
					this.SendPropertyChanged("usernamerejected");
					this.OnusernamerejectedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aidrejected", DbType="Int")]
		public System.Nullable<int> aidrejected
		{
			get
			{
				return this._aidrejected;
			}
			set
			{
				if ((this._aidrejected != value))
				{
					this.OnaidrejectedChanging(value);
					this.SendPropertyChanging();
					this._aidrejected = value;
					this.SendPropertyChanged("aidrejected");
					this.OnaidrejectedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_FreelancersBook_JobsHired")]
	public partial class Table_FreelancersBook_JobsHired : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _jobid;
		
		private string _usernamehired;
		
		private System.Nullable<int> _aidhired;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnjobidChanging(System.Nullable<int> value);
    partial void OnjobidChanged();
    partial void OnusernamehiredChanging(string value);
    partial void OnusernamehiredChanged();
    partial void OnaidhiredChanging(System.Nullable<int> value);
    partial void OnaidhiredChanged();
    #endregion
		
		public Table_FreelancersBook_JobsHired()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobid", DbType="Int")]
		public System.Nullable<int> jobid
		{
			get
			{
				return this._jobid;
			}
			set
			{
				if ((this._jobid != value))
				{
					this.OnjobidChanging(value);
					this.SendPropertyChanging();
					this._jobid = value;
					this.SendPropertyChanged("jobid");
					this.OnjobidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usernamehired", DbType="NVarChar(1500)")]
		public string usernamehired
		{
			get
			{
				return this._usernamehired;
			}
			set
			{
				if ((this._usernamehired != value))
				{
					this.OnusernamehiredChanging(value);
					this.SendPropertyChanging();
					this._usernamehired = value;
					this.SendPropertyChanged("usernamehired");
					this.OnusernamehiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aidhired", DbType="Int")]
		public System.Nullable<int> aidhired
		{
			get
			{
				return this._aidhired;
			}
			set
			{
				if ((this._aidhired != value))
				{
					this.OnaidhiredChanging(value);
					this.SendPropertyChanging();
					this._aidhired = value;
					this.SendPropertyChanged("aidhired");
					this.OnaidhiredChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_FreelancersBook_Jobs")]
	public partial class Table_FreelancersBook_Job : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _active;
		
		private string _title;
		
		private string _shortdesc;
		
		private string _longdesc;
		
		private string _category;
		
		private string _subcategory;
		
		private string _keywords;
		
		private string _budget;
		
		private string _numberoffreelancersneeded;
		
		private string _duration;
		
		private string _skillsrequired;
		
		private string _location;
		
		private string _tutorialurl;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _jobtype;
		
		private string _paymenttype;
		
		private System.Nullable<int> _owneraid;
		
		private string _ownerusername;
		
		private string _profileimage;
		
		private System.Nullable<int> _priority;
		
		private System.Nullable<int> _sponsored;
		
		private System.Nullable<int> _featured;
		
		private System.Nullable<int> _popular;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnactiveChanging(System.Nullable<int> value);
    partial void OnactiveChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnshortdescChanging(string value);
    partial void OnshortdescChanged();
    partial void OnlongdescChanging(string value);
    partial void OnlongdescChanged();
    partial void OncategoryChanging(string value);
    partial void OncategoryChanged();
    partial void OnsubcategoryChanging(string value);
    partial void OnsubcategoryChanged();
    partial void OnkeywordsChanging(string value);
    partial void OnkeywordsChanged();
    partial void OnbudgetChanging(string value);
    partial void OnbudgetChanged();
    partial void OnnumberoffreelancersneededChanging(string value);
    partial void OnnumberoffreelancersneededChanged();
    partial void OndurationChanging(string value);
    partial void OndurationChanged();
    partial void OnskillsrequiredChanging(string value);
    partial void OnskillsrequiredChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OntutorialurlChanging(string value);
    partial void OntutorialurlChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnjobtypeChanging(string value);
    partial void OnjobtypeChanged();
    partial void OnpaymenttypeChanging(string value);
    partial void OnpaymenttypeChanged();
    partial void OnowneraidChanging(System.Nullable<int> value);
    partial void OnowneraidChanged();
    partial void OnownerusernameChanging(string value);
    partial void OnownerusernameChanged();
    partial void OnprofileimageChanging(string value);
    partial void OnprofileimageChanged();
    partial void OnpriorityChanging(System.Nullable<int> value);
    partial void OnpriorityChanged();
    partial void OnsponsoredChanging(System.Nullable<int> value);
    partial void OnsponsoredChanged();
    partial void OnfeaturedChanging(System.Nullable<int> value);
    partial void OnfeaturedChanged();
    partial void OnpopularChanging(System.Nullable<int> value);
    partial void OnpopularChanged();
    #endregion
		
		public Table_FreelancersBook_Job()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Int")]
		public System.Nullable<int> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(1500)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortdesc", DbType="NVarChar(2500)")]
		public string shortdesc
		{
			get
			{
				return this._shortdesc;
			}
			set
			{
				if ((this._shortdesc != value))
				{
					this.OnshortdescChanging(value);
					this.SendPropertyChanging();
					this._shortdesc = value;
					this.SendPropertyChanged("shortdesc");
					this.OnshortdescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longdesc", DbType="NVarChar(MAX)")]
		public string longdesc
		{
			get
			{
				return this._longdesc;
			}
			set
			{
				if ((this._longdesc != value))
				{
					this.OnlongdescChanging(value);
					this.SendPropertyChanging();
					this._longdesc = value;
					this.SendPropertyChanged("longdesc");
					this.OnlongdescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="NVarChar(1500)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subcategory", DbType="NVarChar(1500)")]
		public string subcategory
		{
			get
			{
				return this._subcategory;
			}
			set
			{
				if ((this._subcategory != value))
				{
					this.OnsubcategoryChanging(value);
					this.SendPropertyChanging();
					this._subcategory = value;
					this.SendPropertyChanged("subcategory");
					this.OnsubcategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keywords", DbType="NVarChar(2500)")]
		public string keywords
		{
			get
			{
				return this._keywords;
			}
			set
			{
				if ((this._keywords != value))
				{
					this.OnkeywordsChanging(value);
					this.SendPropertyChanging();
					this._keywords = value;
					this.SendPropertyChanged("keywords");
					this.OnkeywordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_budget", DbType="NVarChar(2500)")]
		public string budget
		{
			get
			{
				return this._budget;
			}
			set
			{
				if ((this._budget != value))
				{
					this.OnbudgetChanging(value);
					this.SendPropertyChanging();
					this._budget = value;
					this.SendPropertyChanged("budget");
					this.OnbudgetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numberoffreelancersneeded", DbType="NVarChar(2500)")]
		public string numberoffreelancersneeded
		{
			get
			{
				return this._numberoffreelancersneeded;
			}
			set
			{
				if ((this._numberoffreelancersneeded != value))
				{
					this.OnnumberoffreelancersneededChanging(value);
					this.SendPropertyChanging();
					this._numberoffreelancersneeded = value;
					this.SendPropertyChanged("numberoffreelancersneeded");
					this.OnnumberoffreelancersneededChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="NVarChar(1500)")]
		public string duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this.OndurationChanging(value);
					this.SendPropertyChanging();
					this._duration = value;
					this.SendPropertyChanged("duration");
					this.OndurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skillsrequired", DbType="NVarChar(2500)")]
		public string skillsrequired
		{
			get
			{
				return this._skillsrequired;
			}
			set
			{
				if ((this._skillsrequired != value))
				{
					this.OnskillsrequiredChanging(value);
					this.SendPropertyChanging();
					this._skillsrequired = value;
					this.SendPropertyChanged("skillsrequired");
					this.OnskillsrequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(1500)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tutorialurl", DbType="NVarChar(3500)")]
		public string tutorialurl
		{
			get
			{
				return this._tutorialurl;
			}
			set
			{
				if ((this._tutorialurl != value))
				{
					this.OntutorialurlChanging(value);
					this.SendPropertyChanging();
					this._tutorialurl = value;
					this.SendPropertyChanged("tutorialurl");
					this.OntutorialurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobtype", DbType="NVarChar(2500)")]
		public string jobtype
		{
			get
			{
				return this._jobtype;
			}
			set
			{
				if ((this._jobtype != value))
				{
					this.OnjobtypeChanging(value);
					this.SendPropertyChanging();
					this._jobtype = value;
					this.SendPropertyChanged("jobtype");
					this.OnjobtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymenttype", DbType="NVarChar(2500)")]
		public string paymenttype
		{
			get
			{
				return this._paymenttype;
			}
			set
			{
				if ((this._paymenttype != value))
				{
					this.OnpaymenttypeChanging(value);
					this.SendPropertyChanging();
					this._paymenttype = value;
					this.SendPropertyChanged("paymenttype");
					this.OnpaymenttypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owneraid", DbType="Int")]
		public System.Nullable<int> owneraid
		{
			get
			{
				return this._owneraid;
			}
			set
			{
				if ((this._owneraid != value))
				{
					this.OnowneraidChanging(value);
					this.SendPropertyChanging();
					this._owneraid = value;
					this.SendPropertyChanged("owneraid");
					this.OnowneraidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ownerusername", DbType="NVarChar(1500)")]
		public string ownerusername
		{
			get
			{
				return this._ownerusername;
			}
			set
			{
				if ((this._ownerusername != value))
				{
					this.OnownerusernameChanging(value);
					this.SendPropertyChanging();
					this._ownerusername = value;
					this.SendPropertyChanged("ownerusername");
					this.OnownerusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profileimage", DbType="NVarChar(3500)")]
		public string profileimage
		{
			get
			{
				return this._profileimage;
			}
			set
			{
				if ((this._profileimage != value))
				{
					this.OnprofileimageChanging(value);
					this.SendPropertyChanging();
					this._profileimage = value;
					this.SendPropertyChanged("profileimage");
					this.OnprofileimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priority", DbType="Int")]
		public System.Nullable<int> priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				if ((this._priority != value))
				{
					this.OnpriorityChanging(value);
					this.SendPropertyChanging();
					this._priority = value;
					this.SendPropertyChanged("priority");
					this.OnpriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sponsored", DbType="Int")]
		public System.Nullable<int> sponsored
		{
			get
			{
				return this._sponsored;
			}
			set
			{
				if ((this._sponsored != value))
				{
					this.OnsponsoredChanging(value);
					this.SendPropertyChanging();
					this._sponsored = value;
					this.SendPropertyChanged("sponsored");
					this.OnsponsoredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_featured", DbType="Int")]
		public System.Nullable<int> featured
		{
			get
			{
				return this._featured;
			}
			set
			{
				if ((this._featured != value))
				{
					this.OnfeaturedChanging(value);
					this.SendPropertyChanging();
					this._featured = value;
					this.SendPropertyChanged("featured");
					this.OnfeaturedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_popular", DbType="Int")]
		public System.Nullable<int> popular
		{
			get
			{
				return this._popular;
			}
			set
			{
				if ((this._popular != value))
				{
					this.OnpopularChanging(value);
					this.SendPropertyChanging();
					this._popular = value;
					this.SendPropertyChanged("popular");
					this.OnpopularChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
