#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancersBook
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="adsrush")]
	public partial class jobszoneDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_FreelancersBook_JobsZoneMessage(Table_FreelancersBook_JobsZoneMessage instance);
    partial void UpdateTable_FreelancersBook_JobsZoneMessage(Table_FreelancersBook_JobsZoneMessage instance);
    partial void DeleteTable_FreelancersBook_JobsZoneMessage(Table_FreelancersBook_JobsZoneMessage instance);
    #endregion
		
		public jobszoneDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["adsrushConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public jobszoneDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public jobszoneDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public jobszoneDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public jobszoneDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_FreelancersBook_JobsZoneMessage> Table_FreelancersBook_JobsZoneMessages
		{
			get
			{
				return this.GetTable<Table_FreelancersBook_JobsZoneMessage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_FreelancersBook_JobsZoneMessages")]
	public partial class Table_FreelancersBook_JobsZoneMessage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _jobid;
		
		private System.Nullable<int> _senderaid;
		
		private System.Nullable<int> _recieveraid;
		
		private string _senderusername;
		
		private string _recieverusername;
		
		private string _kind;
		
		private string _body;
		
		private string _link;
		
		private string _clip;
		
		private string _filepath;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnjobidChanging(System.Nullable<int> value);
    partial void OnjobidChanged();
    partial void OnsenderaidChanging(System.Nullable<int> value);
    partial void OnsenderaidChanged();
    partial void OnrecieveraidChanging(System.Nullable<int> value);
    partial void OnrecieveraidChanged();
    partial void OnsenderusernameChanging(string value);
    partial void OnsenderusernameChanged();
    partial void OnrecieverusernameChanging(string value);
    partial void OnrecieverusernameChanged();
    partial void OnkindChanging(string value);
    partial void OnkindChanged();
    partial void OnbodyChanging(string value);
    partial void OnbodyChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnclipChanging(string value);
    partial void OnclipChanged();
    partial void OnfilepathChanging(string value);
    partial void OnfilepathChanged();
    #endregion
		
		public Table_FreelancersBook_JobsZoneMessage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobid", DbType="Int")]
		public System.Nullable<int> jobid
		{
			get
			{
				return this._jobid;
			}
			set
			{
				if ((this._jobid != value))
				{
					this.OnjobidChanging(value);
					this.SendPropertyChanging();
					this._jobid = value;
					this.SendPropertyChanged("jobid");
					this.OnjobidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderaid", DbType="Int")]
		public System.Nullable<int> senderaid
		{
			get
			{
				return this._senderaid;
			}
			set
			{
				if ((this._senderaid != value))
				{
					this.OnsenderaidChanging(value);
					this.SendPropertyChanging();
					this._senderaid = value;
					this.SendPropertyChanged("senderaid");
					this.OnsenderaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieveraid", DbType="Int")]
		public System.Nullable<int> recieveraid
		{
			get
			{
				return this._recieveraid;
			}
			set
			{
				if ((this._recieveraid != value))
				{
					this.OnrecieveraidChanging(value);
					this.SendPropertyChanging();
					this._recieveraid = value;
					this.SendPropertyChanged("recieveraid");
					this.OnrecieveraidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderusername", DbType="NVarChar(1500)")]
		public string senderusername
		{
			get
			{
				return this._senderusername;
			}
			set
			{
				if ((this._senderusername != value))
				{
					this.OnsenderusernameChanging(value);
					this.SendPropertyChanging();
					this._senderusername = value;
					this.SendPropertyChanged("senderusername");
					this.OnsenderusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieverusername", DbType="NVarChar(1500)")]
		public string recieverusername
		{
			get
			{
				return this._recieverusername;
			}
			set
			{
				if ((this._recieverusername != value))
				{
					this.OnrecieverusernameChanging(value);
					this.SendPropertyChanging();
					this._recieverusername = value;
					this.SendPropertyChanged("recieverusername");
					this.OnrecieverusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kind", DbType="NVarChar(500)")]
		public string kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				if ((this._kind != value))
				{
					this.OnkindChanging(value);
					this.SendPropertyChanging();
					this._kind = value;
					this.SendPropertyChanged("kind");
					this.OnkindChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_body", DbType="NVarChar(MAX)")]
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				if ((this._body != value))
				{
					this.OnbodyChanging(value);
					this.SendPropertyChanging();
					this._body = value;
					this.SendPropertyChanged("body");
					this.OnbodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(2500)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clip", DbType="NVarChar(2500)")]
		public string clip
		{
			get
			{
				return this._clip;
			}
			set
			{
				if ((this._clip != value))
				{
					this.OnclipChanging(value);
					this.SendPropertyChanging();
					this._clip = value;
					this.SendPropertyChanged("clip");
					this.OnclipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filepath", DbType="NVarChar(4000)")]
		public string filepath
		{
			get
			{
				return this._filepath;
			}
			set
			{
				if ((this._filepath != value))
				{
					this.OnfilepathChanging(value);
					this.SendPropertyChanging();
					this._filepath = value;
					this.SendPropertyChanged("filepath");
					this.OnfilepathChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
