#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancersBook
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="adsrush")]
	public partial class moneyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_FreelancersBook_JobsZoneSafeBox(Table_FreelancersBook_JobsZoneSafeBox instance);
    partial void UpdateTable_FreelancersBook_JobsZoneSafeBox(Table_FreelancersBook_JobsZoneSafeBox instance);
    partial void DeleteTable_FreelancersBook_JobsZoneSafeBox(Table_FreelancersBook_JobsZoneSafeBox instance);
    partial void InsertTable_FreelancersBook_JobsZoneReleased(Table_FreelancersBook_JobsZoneReleased instance);
    partial void UpdateTable_FreelancersBook_JobsZoneReleased(Table_FreelancersBook_JobsZoneReleased instance);
    partial void DeleteTable_FreelancersBook_JobsZoneReleased(Table_FreelancersBook_JobsZoneReleased instance);
    partial void InsertTable_FreelancersBook_JobsZoneEarning(Table_FreelancersBook_JobsZoneEarning instance);
    partial void UpdateTable_FreelancersBook_JobsZoneEarning(Table_FreelancersBook_JobsZoneEarning instance);
    partial void DeleteTable_FreelancersBook_JobsZoneEarning(Table_FreelancersBook_JobsZoneEarning instance);
    #endregion
		
		public moneyDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["adsrushConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public moneyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public moneyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public moneyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public moneyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_FreelancersBook_JobsZoneSafeBox> Table_FreelancersBook_JobsZoneSafeBoxes
		{
			get
			{
				return this.GetTable<Table_FreelancersBook_JobsZoneSafeBox>();
			}
		}
		
		public System.Data.Linq.Table<Table_FreelancersBook_JobsZoneReleased> Table_FreelancersBook_JobsZoneReleaseds
		{
			get
			{
				return this.GetTable<Table_FreelancersBook_JobsZoneReleased>();
			}
		}
		
		public System.Data.Linq.Table<Table_FreelancersBook_JobsZoneEarning> Table_FreelancersBook_JobsZoneEarnings
		{
			get
			{
				return this.GetTable<Table_FreelancersBook_JobsZoneEarning>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_FreelancersBook_JobsZoneSafeBoxes")]
	public partial class Table_FreelancersBook_JobsZoneSafeBox : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _jobid;
		
		private System.Nullable<float> _safeboxinitialsum;
		
		private System.Nullable<float> _safeboxsumleft;
		
		private System.Nullable<int> _month;
		
		private System.Nullable<int> _year;
		
		private System.Nullable<int> _senderaid;
		
		private string _senderusername;
		
		private string _senderfullname;
		
		private System.Nullable<int> _recieveraid;
		
		private string _recieverusername;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnjobidChanging(System.Nullable<int> value);
    partial void OnjobidChanged();
    partial void OnsafeboxinitialsumChanging(System.Nullable<float> value);
    partial void OnsafeboxinitialsumChanged();
    partial void OnsafeboxsumleftChanging(System.Nullable<float> value);
    partial void OnsafeboxsumleftChanged();
    partial void OnmonthChanging(System.Nullable<int> value);
    partial void OnmonthChanged();
    partial void OnyearChanging(System.Nullable<int> value);
    partial void OnyearChanged();
    partial void OnsenderaidChanging(System.Nullable<int> value);
    partial void OnsenderaidChanged();
    partial void OnsenderusernameChanging(string value);
    partial void OnsenderusernameChanged();
    partial void OnsenderfullnameChanging(string value);
    partial void OnsenderfullnameChanged();
    partial void OnrecieveraidChanging(System.Nullable<int> value);
    partial void OnrecieveraidChanged();
    partial void OnrecieverusernameChanging(string value);
    partial void OnrecieverusernameChanged();
    #endregion
		
		public Table_FreelancersBook_JobsZoneSafeBox()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobid", DbType="Int")]
		public System.Nullable<int> jobid
		{
			get
			{
				return this._jobid;
			}
			set
			{
				if ((this._jobid != value))
				{
					this.OnjobidChanging(value);
					this.SendPropertyChanging();
					this._jobid = value;
					this.SendPropertyChanged("jobid");
					this.OnjobidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_safeboxinitialsum", DbType="Real")]
		public System.Nullable<float> safeboxinitialsum
		{
			get
			{
				return this._safeboxinitialsum;
			}
			set
			{
				if ((this._safeboxinitialsum != value))
				{
					this.OnsafeboxinitialsumChanging(value);
					this.SendPropertyChanging();
					this._safeboxinitialsum = value;
					this.SendPropertyChanged("safeboxinitialsum");
					this.OnsafeboxinitialsumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_safeboxsumleft", DbType="Real")]
		public System.Nullable<float> safeboxsumleft
		{
			get
			{
				return this._safeboxsumleft;
			}
			set
			{
				if ((this._safeboxsumleft != value))
				{
					this.OnsafeboxsumleftChanging(value);
					this.SendPropertyChanging();
					this._safeboxsumleft = value;
					this.SendPropertyChanged("safeboxsumleft");
					this.OnsafeboxsumleftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_month", DbType="Int")]
		public System.Nullable<int> month
		{
			get
			{
				return this._month;
			}
			set
			{
				if ((this._month != value))
				{
					this.OnmonthChanging(value);
					this.SendPropertyChanging();
					this._month = value;
					this.SendPropertyChanged("month");
					this.OnmonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int")]
		public System.Nullable<int> year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderaid", DbType="Int")]
		public System.Nullable<int> senderaid
		{
			get
			{
				return this._senderaid;
			}
			set
			{
				if ((this._senderaid != value))
				{
					this.OnsenderaidChanging(value);
					this.SendPropertyChanging();
					this._senderaid = value;
					this.SendPropertyChanged("senderaid");
					this.OnsenderaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderusername", DbType="NVarChar(1500)")]
		public string senderusername
		{
			get
			{
				return this._senderusername;
			}
			set
			{
				if ((this._senderusername != value))
				{
					this.OnsenderusernameChanging(value);
					this.SendPropertyChanging();
					this._senderusername = value;
					this.SendPropertyChanged("senderusername");
					this.OnsenderusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderfullname", DbType="NVarChar(1500)")]
		public string senderfullname
		{
			get
			{
				return this._senderfullname;
			}
			set
			{
				if ((this._senderfullname != value))
				{
					this.OnsenderfullnameChanging(value);
					this.SendPropertyChanging();
					this._senderfullname = value;
					this.SendPropertyChanged("senderfullname");
					this.OnsenderfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieveraid", DbType="Int")]
		public System.Nullable<int> recieveraid
		{
			get
			{
				return this._recieveraid;
			}
			set
			{
				if ((this._recieveraid != value))
				{
					this.OnrecieveraidChanging(value);
					this.SendPropertyChanging();
					this._recieveraid = value;
					this.SendPropertyChanged("recieveraid");
					this.OnrecieveraidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieverusername", DbType="NVarChar(1500)")]
		public string recieverusername
		{
			get
			{
				return this._recieverusername;
			}
			set
			{
				if ((this._recieverusername != value))
				{
					this.OnrecieverusernameChanging(value);
					this.SendPropertyChanging();
					this._recieverusername = value;
					this.SendPropertyChanged("recieverusername");
					this.OnrecieverusernameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_FreelancersBook_JobsZoneReleased")]
	public partial class Table_FreelancersBook_JobsZoneReleased : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _jobid;
		
		private System.Nullable<float> _fundsreleased;
		
		private System.Nullable<int> _month;
		
		private System.Nullable<int> _year;
		
		private System.Nullable<int> _recieveraid;
		
		private string _recieverusername;
		
		private System.Nullable<int> _senderaid;
		
		private string _senderusername;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnjobidChanging(System.Nullable<int> value);
    partial void OnjobidChanged();
    partial void OnfundsreleasedChanging(System.Nullable<float> value);
    partial void OnfundsreleasedChanged();
    partial void OnmonthChanging(System.Nullable<int> value);
    partial void OnmonthChanged();
    partial void OnyearChanging(System.Nullable<int> value);
    partial void OnyearChanged();
    partial void OnrecieveraidChanging(System.Nullable<int> value);
    partial void OnrecieveraidChanged();
    partial void OnrecieverusernameChanging(string value);
    partial void OnrecieverusernameChanged();
    partial void OnsenderaidChanging(System.Nullable<int> value);
    partial void OnsenderaidChanged();
    partial void OnsenderusernameChanging(string value);
    partial void OnsenderusernameChanged();
    #endregion
		
		public Table_FreelancersBook_JobsZoneReleased()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobid", DbType="Int")]
		public System.Nullable<int> jobid
		{
			get
			{
				return this._jobid;
			}
			set
			{
				if ((this._jobid != value))
				{
					this.OnjobidChanging(value);
					this.SendPropertyChanging();
					this._jobid = value;
					this.SendPropertyChanged("jobid");
					this.OnjobidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fundsreleased", DbType="Real")]
		public System.Nullable<float> fundsreleased
		{
			get
			{
				return this._fundsreleased;
			}
			set
			{
				if ((this._fundsreleased != value))
				{
					this.OnfundsreleasedChanging(value);
					this.SendPropertyChanging();
					this._fundsreleased = value;
					this.SendPropertyChanged("fundsreleased");
					this.OnfundsreleasedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_month", DbType="Int")]
		public System.Nullable<int> month
		{
			get
			{
				return this._month;
			}
			set
			{
				if ((this._month != value))
				{
					this.OnmonthChanging(value);
					this.SendPropertyChanging();
					this._month = value;
					this.SendPropertyChanged("month");
					this.OnmonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int")]
		public System.Nullable<int> year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieveraid", DbType="Int")]
		public System.Nullable<int> recieveraid
		{
			get
			{
				return this._recieveraid;
			}
			set
			{
				if ((this._recieveraid != value))
				{
					this.OnrecieveraidChanging(value);
					this.SendPropertyChanging();
					this._recieveraid = value;
					this.SendPropertyChanged("recieveraid");
					this.OnrecieveraidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieverusername", DbType="NVarChar(1500)")]
		public string recieverusername
		{
			get
			{
				return this._recieverusername;
			}
			set
			{
				if ((this._recieverusername != value))
				{
					this.OnrecieverusernameChanging(value);
					this.SendPropertyChanging();
					this._recieverusername = value;
					this.SendPropertyChanged("recieverusername");
					this.OnrecieverusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderaid", DbType="Int")]
		public System.Nullable<int> senderaid
		{
			get
			{
				return this._senderaid;
			}
			set
			{
				if ((this._senderaid != value))
				{
					this.OnsenderaidChanging(value);
					this.SendPropertyChanging();
					this._senderaid = value;
					this.SendPropertyChanged("senderaid");
					this.OnsenderaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderusername", DbType="NVarChar(1500)")]
		public string senderusername
		{
			get
			{
				return this._senderusername;
			}
			set
			{
				if ((this._senderusername != value))
				{
					this.OnsenderusernameChanging(value);
					this.SendPropertyChanging();
					this._senderusername = value;
					this.SendPropertyChanged("senderusername");
					this.OnsenderusernameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_FreelancersBook_JobsZoneEarnings")]
	public partial class Table_FreelancersBook_JobsZoneEarning : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _jobid;
		
		private System.Nullable<float> _earnings;
		
		private System.Nullable<int> _month;
		
		private System.Nullable<int> _year;
		
		private System.Nullable<int> _recieveraid;
		
		private string _recieverusername;
		
		private System.Nullable<int> _senderaid;
		
		private string _senderusername;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnjobidChanging(System.Nullable<int> value);
    partial void OnjobidChanged();
    partial void OnearningsChanging(System.Nullable<float> value);
    partial void OnearningsChanged();
    partial void OnmonthChanging(System.Nullable<int> value);
    partial void OnmonthChanged();
    partial void OnyearChanging(System.Nullable<int> value);
    partial void OnyearChanged();
    partial void OnrecieveraidChanging(System.Nullable<int> value);
    partial void OnrecieveraidChanged();
    partial void OnrecieverusernameChanging(string value);
    partial void OnrecieverusernameChanged();
    partial void OnsenderaidChanging(System.Nullable<int> value);
    partial void OnsenderaidChanged();
    partial void OnsenderusernameChanging(string value);
    partial void OnsenderusernameChanged();
    #endregion
		
		public Table_FreelancersBook_JobsZoneEarning()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobid", DbType="Int")]
		public System.Nullable<int> jobid
		{
			get
			{
				return this._jobid;
			}
			set
			{
				if ((this._jobid != value))
				{
					this.OnjobidChanging(value);
					this.SendPropertyChanging();
					this._jobid = value;
					this.SendPropertyChanged("jobid");
					this.OnjobidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_earnings", DbType="Real")]
		public System.Nullable<float> earnings
		{
			get
			{
				return this._earnings;
			}
			set
			{
				if ((this._earnings != value))
				{
					this.OnearningsChanging(value);
					this.SendPropertyChanging();
					this._earnings = value;
					this.SendPropertyChanged("earnings");
					this.OnearningsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_month", DbType="Int")]
		public System.Nullable<int> month
		{
			get
			{
				return this._month;
			}
			set
			{
				if ((this._month != value))
				{
					this.OnmonthChanging(value);
					this.SendPropertyChanging();
					this._month = value;
					this.SendPropertyChanged("month");
					this.OnmonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int")]
		public System.Nullable<int> year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieveraid", DbType="Int")]
		public System.Nullable<int> recieveraid
		{
			get
			{
				return this._recieveraid;
			}
			set
			{
				if ((this._recieveraid != value))
				{
					this.OnrecieveraidChanging(value);
					this.SendPropertyChanging();
					this._recieveraid = value;
					this.SendPropertyChanged("recieveraid");
					this.OnrecieveraidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieverusername", DbType="NVarChar(1500)")]
		public string recieverusername
		{
			get
			{
				return this._recieverusername;
			}
			set
			{
				if ((this._recieverusername != value))
				{
					this.OnrecieverusernameChanging(value);
					this.SendPropertyChanging();
					this._recieverusername = value;
					this.SendPropertyChanged("recieverusername");
					this.OnrecieverusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderaid", DbType="Int")]
		public System.Nullable<int> senderaid
		{
			get
			{
				return this._senderaid;
			}
			set
			{
				if ((this._senderaid != value))
				{
					this.OnsenderaidChanging(value);
					this.SendPropertyChanging();
					this._senderaid = value;
					this.SendPropertyChanged("senderaid");
					this.OnsenderaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderusername", DbType="NVarChar(1500)")]
		public string senderusername
		{
			get
			{
				return this._senderusername;
			}
			set
			{
				if ((this._senderusername != value))
				{
					this.OnsenderusernameChanging(value);
					this.SendPropertyChanging();
					this._senderusername = value;
					this.SendPropertyChanged("senderusername");
					this.OnsenderusernameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
