<?xml version="1.0" encoding="utf-8"?><Database Name="adsrush" Class="usersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=adsrush.database.windows.net;Initial Catalog=adsrush;User ID=tamordy;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="adsrushConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Table_FreelancersBook_Users" Member="Table_FreelancersBook_Users">
    <Type Name="Table_FreelancersBook_User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="signupdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="aid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="suspended" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="emailconfirmed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="identityconfirmed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="contactconfirmed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phoneconfirmed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="referaid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="referusername" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="experience" Type="System.String" DbType="NVarChar(3500)" CanBeNull="true" />
      <Column Name="skype" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="facebook" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="linkedin" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="whatsapp" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="profileimage" Type="System.String" DbType="NVarChar(3500)" CanBeNull="true" />
      <Column Name="website" Type="System.String" DbType="NVarChar(3500)" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="subcategory" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="paymentmethod" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="balance" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="lastpayout" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="lastpayoutdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="company" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(2500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>